import { useState } from "react";
import { Download, Check, ChevronDown } from "lucide-react";
import type { SummarizationResult, ContributionsResponse } from "../types.ts";

interface Props {
  summary: SummarizationResult | null;
  contributions: ContributionsResponse | null;
}

export function ExportButton({ summary, contributions }: Props) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!contributions) return null;

  const exportMarkdown = () => {
    let md = "# Ship Log\n\n";

    if (summary?.rollupSummary) {
      md += `## Summary\n\n${summary.rollupSummary}\n\n---\n\n`;
    }

    if (summary?.groupSummaries) {
      for (const gs of summary.groupSummaries) {
        md += `### ${gs.groupLabel}\n\n${gs.summary}\n\n`;
      }
    }

    md += `\n---\n\n*Generated by shiplog*\n`;
    downloadFile("shiplog-report.md", md, "text/markdown");
    setOpen(false);
  };

  const exportJSON = () => {
    const data = { contributions, summary };
    downloadFile(
      "shiplog-data.json",
      JSON.stringify(data, null, 2),
      "application/json"
    );
    setOpen(false);
  };

  const copyToClipboard = async () => {
    const text = summary?.rollupSummary ?? "No summary available";
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    setOpen(false);
  };

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs text-neutral-400 bg-neutral-800/50 border border-neutral-700/40 hover:bg-neutral-800 hover:text-neutral-300 transition-colors"
      >
        <Download className="w-3 h-3" />
        Export
        <ChevronDown className="w-3 h-3" />
      </button>

      {open && (
        <>
          <div
            className="fixed inset-0 z-10"
            onClick={() => setOpen(false)}
          />
          <div className="absolute right-0 top-full mt-1 z-20 w-44 bg-neutral-900 border border-neutral-700/50 rounded-lg shadow-xl overflow-hidden">
            <button
              onClick={exportMarkdown}
              className="w-full px-3 py-2 text-xs text-left text-neutral-300 hover:bg-neutral-800/80 transition-colors"
            >
              Export as Markdown
            </button>
            <button
              onClick={exportJSON}
              className="w-full px-3 py-2 text-xs text-left text-neutral-300 hover:bg-neutral-800/80 transition-colors"
            >
              Export as JSON
            </button>
            <div className="h-px bg-neutral-800" />
            <button
              onClick={copyToClipboard}
              className="w-full px-3 py-2 text-xs text-left text-neutral-300 hover:bg-neutral-800/80 transition-colors flex items-center gap-2"
            >
              {copied ? (
                <>
                  <Check className="w-3 h-3 text-emerald-400" />
                  Copied!
                </>
              ) : (
                "Copy summary"
              )}
            </button>
          </div>
        </>
      )}
    </div>
  );
}

function downloadFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
