// CLI output renderers for headless mode
// Phase 7: Export & Output

import type { CommitGroup } from "../core/grouping.ts";
import type { SummarizationResult, GroupSummary } from "../core/summarizer.ts";

interface OutputData {
  groups: CommitGroup[];
  summary: SummarizationResult | null;
  params: { from: string; to: string; repos: string[] };
  stats: Record<string, number | boolean>;
}

// ── Markdown ──

export function renderMarkdown(data: OutputData): string {
  const { groups, summary, params, stats } = data;
  const lines: string[] = [];

  lines.push("# Ship Log\n");
  lines.push(`**Period:** ${params.from} to ${params.to}`);
  lines.push(`**Repositories:** ${params.repos.join(", ")}\n`);
  lines.push("---\n");

  // Roll-up summary
  if (summary?.rollupSummary) {
    lines.push("## Summary\n");
    lines.push(summary.rollupSummary);
    lines.push("\n---\n");
  }

  // Group summaries
  const prGroups = groups.filter((g) => g.type === "pr");
  const orphanGroups = groups.filter((g) => g.type === "orphan");

  if (prGroups.length > 0) {
    lines.push("## Pull Requests\n");
    for (const group of prGroups) {
      const gs = findGroupSummary(summary, group.label);
      const pr = group.pr;
      lines.push(`### ${group.label}\n`);
      if (pr) {
        lines.push(
          `**Repo:** ${pr.repo} | **Commits:** ${group.commits.length} | **${pr.state}**${pr.mergedAt ? ` on ${pr.mergedAt.split("T")[0]}` : ""}\n`,
        );
      }
      if (gs?.summary) {
        lines.push(gs.summary);
      }
      lines.push("");
    }
  }

  if (orphanGroups.length > 0) {
    lines.push("## Direct Commits\n");
    for (const group of orphanGroups) {
      const gs = findGroupSummary(summary, group.label);
      lines.push(`### ${group.label}\n`);
      if (gs?.summary) {
        lines.push(gs.summary);
      } else {
        for (const c of group.commits) {
          lines.push(`- \`${c.sha.slice(0, 7)}\` ${c.message}`);
        }
      }
      lines.push("");
    }
  }

  // Stats
  lines.push("---\n");
  lines.push("## Statistics\n");
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(`| Commits | ${stats.totalCommits ?? 0} |`);
  lines.push(`| Pull requests | ${stats.totalPRs ?? 0} |`);
  lines.push(`| Files changed | ${stats.filesChanged ?? 0} |`);
  lines.push(`| Repos | ${stats.reposProcessed ?? 0} |`);
  if (stats.duplicatesRemoved) {
    lines.push(`| Duplicates removed | ${stats.duplicatesRemoved} |`);
  }
  lines.push("");

  lines.push("---\n");
  lines.push(`*Generated by shiplog on ${new Date().toISOString().split("T")[0]}*\n`);

  return lines.join("\n");
}

// ── JSON ──

export function renderJSON(data: OutputData): string {
  return JSON.stringify(
    {
      meta: {
        generator: "shiplog",
        generatedAt: new Date().toISOString(),
        ...data.params,
      },
      stats: data.stats,
      groups: data.groups.map((g) => ({
        type: g.type,
        label: g.label,
        pr: g.pr
          ? { number: g.pr.number, title: g.pr.title, state: g.pr.state, repo: g.pr.repo }
          : undefined,
        commitCount: g.commits.length,
        commits: g.commits.map((c) => ({
          sha: c.sha,
          message: c.message,
          author: c.author,
          date: c.date,
          repo: c.repo,
          files: c.files,
        })),
        summary: findGroupSummary(data.summary, g.label)?.summary ?? null,
      })),
      rollupSummary: data.summary?.rollupSummary ?? null,
      summaryStats: data.summary?.stats ?? null,
    },
    null,
    2,
  );
}

// ── HTML ──

export function renderHTML(data: OutputData): string {
  const { groups, summary, params, stats } = data;

  const escape = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const mdToHtml = (md: string) =>
    escape(md)
      .replace(/^### (.+)$/gm, "<h3>$1</h3>")
      .replace(/^## (.+)$/gm, "<h2>$1</h2>")
      .replace(/^# (.+)$/gm, "<h1>$1</h1>")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/`(.+?)`/g, '<code>$1</code>')
      .replace(/^- (.+)$/gm, "<li>$1</li>")
      .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
      .replace(/\n\n/g, "</p><p>")
      .replace(/^(?!<[hul])/gm, "<p>")
      .replace(/$(?!<\/[hul])/gm, "</p>")
      .replace(/<p><\/p>/g, "");

  let body = "";

  // Header
  body += `<header><h1>Ship Log</h1>`;
  body += `<div class="meta">${params.from} — ${params.to} · ${params.repos.join(", ")}</div>`;
  body += `</header>`;

  // Roll-up
  if (summary?.rollupSummary) {
    body += `<section class="rollup"><div class="accent-bar"></div>`;
    body += `<h2>Summary</h2><div class="content">${mdToHtml(summary.rollupSummary)}</div>`;
    body += `</section>`;
  }

  // Stats
  body += `<section class="stats-grid">`;
  const num = (v: number | boolean | undefined) => (typeof v === "number" ? v : 0);
  body += statBox("Commits", num(stats.totalCommits));
  body += statBox("Pull Requests", num(stats.totalPRs));
  body += statBox("Files Changed", num(stats.filesChanged));
  body += statBox("Repos", num(stats.reposProcessed));
  body += `</section>`;

  // Groups
  for (const group of groups) {
    const gs = findGroupSummary(summary, group.label);
    const badge = group.type === "pr" ? group.pr?.state ?? "pr" : "orphan";
    const badgeClass = badge === "merged" ? "merged" : badge === "open" ? "open" : badge === "closed" ? "closed" : "orphan";

    body += `<section class="group">`;
    body += `<div class="group-header">`;
    body += `<span class="badge ${badgeClass}">${badge}</span>`;
    body += `<span class="group-label">${escape(group.label)}</span>`;
    body += `<span class="group-meta">${group.commits.length} commits</span>`;
    body += `</div>`;
    if (gs?.summary) {
      body += `<div class="group-summary content">${mdToHtml(gs.summary)}</div>`;
    }
    body += `</section>`;
  }

  // Footer
  body += `<footer>Generated by shiplog on ${new Date().toISOString().split("T")[0]}</footer>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Ship Log — ${params.from} to ${params.to}</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:"Segoe UI",system-ui,-apple-system,sans-serif;background:#0a0a0f;color:#d4d4d8;line-height:1.7;max-width:800px;margin:0 auto;padding:2rem 1.5rem}
  h1{font-size:1.75rem;font-weight:700;color:#f4f4f5;margin-bottom:0.25rem}
  h2{font-size:1.15rem;font-weight:600;color:#e4e4e7;margin-bottom:0.5rem}
  h3{font-size:1rem;font-weight:600;color:#d4d4d8;margin-top:1rem}
  header{margin-bottom:2rem;padding-bottom:1.5rem;border-bottom:1px solid #27272a}
  .meta{font-size:0.8rem;color:#71717a;font-family:monospace}
  .rollup{background:#18181b;border:1px solid #27272a;border-radius:12px;padding:1.25rem;margin-bottom:1.5rem;position:relative;overflow:hidden}
  .rollup .accent-bar{position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,#22d3ee 0%,#a855f7 50%,transparent 100%)}
  .content p{margin-bottom:0.6rem;color:#a1a1aa}
  .content strong{color:#e4e4e7}
  .content code{background:#27272a;padding:0.1em 0.35em;border-radius:3px;font-size:0.85em;color:#22d3ee}
  .content ul{margin:0.5rem 0 0.5rem 1.25rem}
  .content li{margin-bottom:0.2rem;color:#a1a1aa}
  .stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:0.75rem;margin-bottom:1.5rem}
  .stat-box{background:#18181b;border:1px solid #27272a;border-radius:10px;padding:0.75rem 1rem}
  .stat-label{font-size:0.65rem;text-transform:uppercase;letter-spacing:0.08em;color:#71717a;font-weight:600}
  .stat-value{font-size:1.5rem;font-weight:700;color:#f4f4f5;font-family:monospace}
  .group{background:#18181b;border:1px solid #27272a;border-radius:10px;padding:1rem;margin-bottom:0.75rem}
  .group-header{display:flex;align-items:center;gap:0.5rem;flex-wrap:wrap}
  .badge{font-size:0.6rem;text-transform:uppercase;letter-spacing:0.06em;font-weight:700;padding:0.15rem 0.5rem;border-radius:4px}
  .badge.merged{background:#7c3aed20;color:#c084fc;border:1px solid #7c3aed30}
  .badge.open{background:#10b98120;color:#34d399;border:1px solid #10b98130}
  .badge.closed{background:#ef444420;color:#f87171;border:1px solid #ef444430}
  .badge.orphan{background:#f59e0b20;color:#fbbf24;border:1px solid #f59e0b30}
  .group-label{font-weight:600;color:#e4e4e7;font-size:0.9rem}
  .group-meta{font-size:0.75rem;color:#52525b;font-family:monospace;margin-left:auto}
  .group-summary{margin-top:0.75rem;padding-top:0.75rem;border-top:1px solid #27272a}
  footer{margin-top:2rem;padding-top:1rem;border-top:1px solid #27272a;font-size:0.75rem;color:#52525b;text-align:center}
  @media(max-width:640px){.stats-grid{grid-template-columns:repeat(2,1fr)}}
</style>
</head>
<body>
${body}
</body>
</html>`;
}

function statBox(label: string, value: number): string {
  return `<div class="stat-box"><div class="stat-label">${label}</div><div class="stat-value">${value.toLocaleString()}</div></div>`;
}

function findGroupSummary(
  summary: SummarizationResult | null,
  label: string,
): GroupSummary | undefined {
  return summary?.groupSummaries?.find((g) => g.groupLabel === label);
}
